export const FILES_ADD_TO_BENEFISIER_LIST = "FILES_ADD_TO_BENEFISIER_LIST";
export const LIST_ADD_TO_BENEFISIER_LIST = "LIST_ADD_TO_BENEFISIER_LIST";
export const FILES_DELETE_FROM_BENEFISIER_LIST =
  "FILES_DELETE_FROM_BENEFISIER_LIST";
export const DELETE_BENEFISIER_LIST = "DELETE_BENEFISIER_LIST";
