export const COMMUNE_ADD_REQUEST = "COMMUNE_ADD_REQUEST";
export const COMMUNE_ADD_SUCCESS = "COMMUNE_ADD_SUCCESS";
export const COMMUNE_ADD_FAIL = "COMMUNE_ADD_FAIL";

export const COMMUNE_LIST_REQUEST = "COMMUNE_LIST_REQUEST";
export const COMMUNE_LIST_SUCCESS = "COMMUNE_LIST_SUCCESS";
export const COMMUNE_LIST_FAIL = "COMMUNE_LIST_FAIL";

export const COMMUNE_UPDATE_REQUEST = "COMMUNE_UPDATE_REQUEST";
export const COMMUNE_UPDATE_SUCCESS = "COMMUNE_UPDATE_SUCCESS";
export const COMMUNE_UPDATE_FAIL = "COMMUNE_UPDATE_FAIL";

export const COMMUNE_DELETE_REQUEST = "COMMUNE_DELETE_REQUEST";
export const COMMUNE_DELETE_SUCCESS = "COMMUNE_DELETE_SUCCESS";
export const COMMUNE_DELETE_FAIL = "COMMUNE_DELETE_FAIL";

export const COMMUNE_GET_REQUEST = "COMMUNE_GET_REQUEST";
export const COMMUNE_GET_SUCCESS = "COMMUNE_GET_SUCCESS";
export const COMMUNE_GET_FAIL = "COMMUNE_GET_FAIL";

export const COMMUNE_GETW_REQUEST = "COMMUNE_GETW_REQUEST";
export const COMMUNE_GETW_SUCCESS = "COMMUNE_GETW_SUCCESS";
export const COMMUNE_GETW_FAIL = "COMMUNE_GETW_FAIL";