export const DAIRA_ADD_REQUEST = "DAIRA_ADD_REQUEST";
export const DAIRA_ADD_SUCCESS = "DAIRA_ADD_SUCCESS";
export const DAIRA_ADD_FAIL = "DAIRA_ADD_FAIL";

export const DAIRA_LIST_REQUEST = "DAIRA_LIST_REQUEST";
export const DAIRA_LIST_SUCCESS = "DAIRA_LIST_SUCCESS";
export const DAIRA_LIST_FAIL = "DAIRA_LIST_FAIL";

export const DAIRA_UPDATE_REQUEST = "DAIRA_UPDATE_REQUEST";
export const DAIRA_UPDATE_SUCCESS = "DAIRA_UPDATE_SUCCESS";
export const DAIRA_UPDATE_FAIL = "DAIRA_UPDATE_FAIL";

export const DAIRA_DELETE_REQUEST = "DAIRA_DELETE_REQUEST";
export const DAIRA_DELETE_SUCCESS = "DAIRA_DELETE_SUCCESS";
export const DAIRA_DELETE_FAIL = "DAIRA_DELETE_FAIL";

export const DAIRA_GET_REQUEST = "DAIRA_GET_REQUEST";
export const DAIRA_GET_SUCCESS = "DAIRA_GET_SUCCESS";
export const DAIRA_GET_FAIL = "DAIRA_GET_FAIL";

export const DAIRA_GETW_REQUEST = "DAIRA_GETW_REQUEST";
export const DAIRA_GETW_SUCCESS = "DAIRA_GETW_SUCCESS";
export const DAIRA_GETW_FAIL = "DAIRA_GETW_FAIL";
