export const DEMANDEUR_ADD_REQUEST = "DEMANDEUR_ADD_REQUEST";
export const DEMANDEUR_ADD_SUCCESS = "DEMANDEUR_ADD_SUCCESS";
export const DEMANDEUR_ADD_FAIL = "DEMANDEUR_ADD_FAIL";

export const DEMANDEUR_LIST_REQUEST = "DEMANDEUR_LIST_REQUEST";
export const DEMANDEUR_LIST_SUCCESS = "DEMANDEUR_LIST_SUCCESS";
export const DEMANDEUR_LIST_FAIL = "DEMANDEUR_LIST_FAIL";

export const DEMANDEUR_UPDATE_REQUEST = "DEMANDEUR_UPDATE_REQUEST";
export const DEMANDEUR_UPDATE_SUCCESS = "DEMANDEUR_UPDATE_SUCCESS";
export const DEMANDEUR_UPDATE_FAIL = "DEMANDEUR_UPDATE_FAIL";

export const DEMANDEUR_DELETE_REQUEST = "DEMANDEUR_DELETE_REQUEST";
export const DEMANDEUR_DELETE_SUCCESS = "DEMANDEUR_DELETE_SUCCESS";
export const DEMANDEUR_DELETE_FAIL = "DEMANDEUR_DELETE_FAIL";

export const DEMANDEUR_GET_REQUEST = "DEMANDEUR_GET_REQUEST";
export const DEMANDEUR_GET_SUCCESS = "DEMANDEUR_GET_SUCCESS";
export const DEMANDEUR_GET_FAIL = "DEMANDEUR_GET_FAIL";