export const DOSSIER_ADD_REQUEST = "DOSSIER_ADD_REQUEST";
export const DOSSIER_ADD_SUCCESS = "DOSSIER_ADD_SUCCESS";
export const DOSSIER_ADD_FAIL = "DOSSIER_ADD_FAIL";

export const DOSSIER_LIST_REQUEST = "DOSSIER_LIST_REQUEST";
export const DOSSIER_LIST_SUCCESS = "DOSSIER_LIST_SUCCESS";
export const DOSSIER_LIST_FAIL = "DOSSIER_LIST_FAIL";

export const DOSSIER_UPDATE_REQUEST = "DOSSIER_UPDATE_REQUEST";
export const DOSSIER_UPDATE_SUCCESS = "DOSSIER_UPDATE_SUCCESS";
export const DOSSIER_UPDATE_FAIL = "DOSSIER_UPDATE_FAIL";

export const DOSSIER_DELETE_REQUEST = "DOSSIER_DELETE_REQUEST";
export const DOSSIER_DELETE_SUCCESS = "DOSSIER_DELETE_SUCCESS";
export const DOSSIER_DELETE_FAIL = "DOSSIER_DELETE_FAIL";

export const DOSSIER_GET_REQUEST = "DOSSIER_GET_REQUEST";
export const DOSSIER_GET_SUCCESS = "DOSSIER_GET_SUCCESS";
export const DOSSIER_GET_FAIL = "DOSSIER_GET_FAIL";