export const ENQUETCNL_LIST_REQUEST = "ENQUETCNL_LIST_REQUEST";
export const ENQUETCNL_LIST_SUCCESS = "ENQUETCNL_LIST_SUCCESS";
export const ENQUETCNL_LIST_FAIL = "ENQUETCNL_LIST_FAIL";

export const ENQUETCNL_GET_REQUEST = "ENQUETCNL_GET_REQUEST";
export const ENQUETCNL_GET_SUCCESS = "ENQUETCNL_GET_SUCCESS";
export const ENQUETCNL_GET_FAIL = "ENQUETCNL_GET_FAIL";

export const ENQUETCNAS_GET_REQUEST = "ENQUETCNAS_GET_REQUEST";
export const ENQUETCNAS_GET_SUCCESS = "ENQUETCNAS_GET_SUCCESS";
export const ENQUETCNAS_GET_FAIL = "ENQUETCNAS_GET_FAIL";

export const ENQUETCASNOS_GET_REQUEST = "ENQUETCASNOS_GET_REQUEST";
export const ENQUETCASNOS_GET_SUCCESS = "ENQUETCASNOS_GET_SUCCESS";
export const ENQUETCASNOS_GET_FAIL = "ENQUETCASNOS_GET_FAIL";
