export const ENQUETCNL_ADD_REQUEST = "ENQUETCNL_ADD_REQUEST";
export const ENQUETCNL_ADD_SUCCESS = "ENQUETCNL_ADD_SUCCESS";
export const ENQUETCNL_ADD_FAIL = "ENQUETCNL_ADD_FAIL";

export const ENQUETCNL_LIST_REQUEST = "ENQUETCNL_LIST_REQUEST";
export const ENQUETCNL_LIST_SUCCESS = "ENQUETCNL_LIST_SUCCESS";
export const ENQUETCNL_LIST_FAIL = "ENQUETCNL_LIST_FAIL";

export const ENQUETCNL_UPDATE_REQUEST = "ENQUETCNL_UPDATE_REQUEST";
export const ENQUETCNL_UPDATE_SUCCESS = "ENQUETCNL_UPDATE_SUCCESS";
export const ENQUETCNL_UPDATE_FAIL = "ENQUETCNL_UPDATE_FAIL";

export const ENQUETCNL_DELETE_REQUEST = "ENQUETCNL_DELETE_REQUEST";
export const ENQUETCNL_DELETE_SUCCESS = "ENQUETCNL_DELETE_SUCCESS";
export const ENQUETCNL_DELETE_FAIL = "ENQUETCNL_DELETE_FAIL";

export const ENQUETCNL_GET_REQUEST = "ENQUETCNL_GET_REQUEST";
export const ENQUETCNL_GET_SUCCESS = "ENQUETCNL_GET_SUCCESS";
export const ENQUETCNL_GET_FAIL = "ENQUETCNL_GET_FAIL";
