export const FILES_ADD_REQUEST = "FILES_ADD_REQUEST";
export const FILES_ADD_SUCCESS = "FILES_ADD_SUCCESS";
export const FILES_ADD_FAIL = "FILES_ADD_FAIL";

export const FILES_LIST_REQUEST = "FILES_LIST_REQUEST";
export const FILES_LIST_SUCCESS = "FILES_LIST_SUCCESS";
export const FILES_LIST_FAIL = "FILES_LIST_FAIL";

export const FILES_UPDATE_REQUEST = "FILES_UPDATE_REQUEST";
export const FILES_UPDATE_SUCCESS = "FILES_UPDATE_SUCCESS";
export const FILES_UPDATE_FAIL = "FILES_UPDATE_FAIL";

export const FILES_DELETE_REQUEST = "FILES_DELETE_REQUEST";
export const FILES_DELETE_SUCCESS = "FILES_DELETE_SUCCESS";
export const FILES_DELETE_FAIL = "FILES_DELETE_FAIL";
