export const IMPORTATIONFICHIER_SEND_REQUEST = "IMPORTATIONFICHIER_SEND_REQUEST";
export const IMPORTATIONFICHIER_SEND_SUCCESS = "IMPORTATIONFICHIER_SEND_SUCCESS";
export const IMPORTATIONFICHIER_SEND_FAIL = "IMPORTATIONFICHIER_SEND_FAIL";
