export const IMPORTATIONDATA_SEND_REQUEST = "IMPORTATIONDATA_SEND_REQUEST";
export const IMPORTATIONDATA_SEND_SUCCESS = "IMPORTATIONDATA_SEND_SUCCESS";
export const IMPORTATIONDATA_SEND_FAIL = "IMPORTATIONDATA_SEND_FAIL";
