export const QUOTA_ADD_REQUEST = "QUOTA_ADD_REQUEST";
export const QUOTA_ADD_SUCCESS = "QUOTA_ADD_SUCCESS";
export const QUOTA_ADD_FAIL = "QUOTA_ADD_FAIL";

export const QUOTA_LIST_REQUEST = "QUOTA_LIST_REQUEST";
export const QUOTA_LIST_SUCCESS = "QUOTA_LIST_SUCCESS";
export const QUOTA_LIST_FAIL = "QUOTA_LIST_FAIL";

export const QUOTA_UPDATE_REQUEST = "QUOTA_UPDATE_REQUEST";
export const QUOTA_UPDATE_SUCCESS = "QUOTA_UPDATE_SUCCESS";
export const QUOTA_UPDATE_FAIL = "QUOTA_UPDATE_FAIL";

export const QUOTA_DELETE_REQUEST = "QUOTA_DELETE_REQUEST";
export const QUOTA_DELETE_SUCCESS = "QUOTA_DELETE_SUCCESS";
export const QUOTA_DELETE_FAIL = "QUOTA_DELETE_FAIL";
