export const SYSTEM_ADD_REQUEST = "SYSTEM_ADD_REQUEST";
export const SYSTEM_ADD_SUCCESS = "SYSTEM_ADD_SUCCESS";
export const SYSTEM_ADD_FAIL = "SYSTEM_ADD_FAIL";

export const SYSTEM_CHECK_REQUEST = "SYSTEM_CHECK_REQUEST";
export const SYSTEM_CHECK_SUCCESS = "SYSTEM_CHECK_SUCCESS";
export const SYSTEM_CHECK_FAIL = "SYSTEM_CHECK_FAIL";

export const SYSTEM_UPDATE_REQUEST = "SYSTEM_UPDATE_REQUEST";
export const SYSTEM_UPDATE_SUCCESS = "SYSTEM_UPDATE_SUCCESS";
export const SYSTEM_UPDATE_FAIL = "SYSTEM_UPDATE_FAIL";
