export const IMPORTATIONFICHIERTEMPLATE_DOWNLOAD_REQUEST =
  "IMPORTATIONFICHIERTEMPLATE_DOWNLOAD_REQUEST";
export const IMPORTATIONFICHIERTEMPLATE_DOWNLOAD_SUCCESS =
  "IMPORTATIONFICHIERTEMPLATE_DOWNLOAD_SUCCESS";
export const IMPORTATIONFICHIERTEMPLATE_DOWNLOAD_FAIL =
  "IMPORTATIONFICHIERTEMPLATE_DOWNLOAD_FAIL";
