export const WILAYA_ADD_REQUEST = "WILAYA_ADD_REQUEST";
export const WILAYA_ADD_SUCCESS = "WILAYA_ADD_SUCCESS";
export const WILAYA_ADD_FAIL = "WILAYA_ADD_FAIL";

export const WILAYA_LIST_REQUEST = "WILAYA_LIST_REQUEST";
export const WILAYA_LIST_SUCCESS = "WILAYA_LIST_SUCCESS";
export const WILAYA_LIST_FAIL = "WILAYA_LIST_FAIL";

export const WILAYA_UPDATE_REQUEST = "WILAYA_UPDATE_REQUEST";
export const WILAYA_UPDATE_SUCCESS = "WILAYA_UPDATE_SUCCESS";
export const WILAYA_UPDATE_FAIL = "WILAYA_UPDATE_FAIL";

export const WILAYA_DELETE_REQUEST = "WILAYA_DELETE_REQUEST";
export const WILAYA_DELETE_SUCCESS = "WILAYA_DELETE_SUCCESS";
export const WILAYA_DELETE_FAIL = "WILAYA_DELETE_FAIL";

export const WILAYA_GET_REQUEST = "WILAYA_GET_REQUEST";
export const WILAYA_GET_SUCCESS = "WILAYA_GET_SUCCESS";
export const WILAYA_GET_FAIL = "WILAYA_GET_FAIL";