const dossiers = [
  {
    id: '0',
    type: "dema",
    prenom: "احمد",
    prenom_fr: "",
    nom: "",
    nom_fr: "",
    gender: "",
    num_act: "",
    date_n: "",
    lieu_n: "",
    lieu_n_fr: "",
    wil_n: 0,
    com_n: 0,
    prenom_p: "",
    prenom_p_fr: "",
    prenom_m: "",
    prenom_m_fr: "",
    nom_m: "",
    nom_m_fr: "",
    num_i_n: "",
    stuation_f: "",
    situation_p: "",
    profession: "",
    salaire: 0,
    creator: 0,
  },
  {
    id: '1',
    type: "",
    prenom: "محمد",
    prenom_fr: "",
    nom: "",
    nom_fr: "",
    gender: "",
    num_act: "",
    date_n: "",
    lieu_n: "",
    lieu_n_fr: "",
    wil_n: 0,
    com_n: 0,
    prenom_p: "",
    prenom_p_fr: "",
    prenom_m: "",
    prenom_m_fr: "",
    nom_m: "",
    nom_m_fr: "",
    num_i_n: "",
    stuation_f: "",
    situation_p: "",
    profession: "",
    salaire: 0,
    creator: 0,
  },
  {
    id: '2',
    type: "",
    prenom: "امين",
    prenom_fr: "",
    nom: "",
    nom_fr: "",
    gender: "",
    num_act: "",
    date_n: "",
    lieu_n: "",
    lieu_n_fr: "",
    wil_n: 0,
    com_n: 0,
    prenom_p: "",
    prenom_p_fr: "",
    prenom_m: "",
    prenom_m_fr: "",
    nom_m: "",
    nom_m_fr: "",
    num_i_n: "",
    stuation_f: "",
    situation_p: "",
    profession: "",
    salaire: 0,
    creator: 0,
  },
  {
    id: '3',
    type: "",
    prenom: "هدى",
    prenom_fr: "",
    nom: "",
    nom_fr: "",
    gender: "",
    num_act: "",
    date_n: "",
    lieu_n: "",
    lieu_n_fr: "",
    wil_n: 0,
    com_n: 0,
    prenom_p: "",
    prenom_p_fr: "",
    prenom_m: "",
    prenom_m_fr: "",
    nom_m: "",
    nom_m_fr: "",
    num_i_n: "",
    stuation_f: "",
    situation_p: "",
    profession: "",
    salaire: 0,
    creator: 0,
  },
];
 module.exports = dossiers;